---
# Default settings for all vms (they can be overridden on each node)
default:
  memory: 1612 # MB or RAM to assign - CentOS Installer needs at leas 1512 MB
  cpu: 1 # Number of vCPU to assign to the VM
  box: debian/bullseye64 # Box used for the VM
  domain: betadots.training # Name of DNS domain for the created machines

# List of nodes shown in vagrant status
nodes:
  server1:
    ip1: 10.100.10.101
    ip2: 172.16.120.10
    additional_disk_size: 10 # size in GB
  server2:
    ip1: 10.100.10.102
    ip2: 172.16.120.11
    additional_disk_size: 10 # size in GB
  server3:
    ip1: 10.100.10.103
    ip2: 172.16.120.12
